tileStack:
  - instances: 2
    northTop: field
    northMid: field
    northBot: field
    westTop: field
    westMid: field
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: field
    eastBot: field
    center: cloister
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: roadEnd
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 4
    northTop: field
    northMid: field
    northBot: field
    westTop: field
    westMid: field
    westBot: field
    southTop: field
    southMid: field
    southBot: field
    eastTop: field
    eastMid: field
    eastBot: field
    center: cloister
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: field
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 1
    northTop: city
    northMid: city
    northBot: cityPennant
    westTop: city
    westMid: city
    westBot: city
    southTop: city
    southMid: city
    southBot: city
    eastTop: city
    eastMid: city
    eastBot: city
    center: city
    centerNE: city
    centerN: city
    centerNW: city
    centerW: city
    centerSW: city
    centerS: city
    centerSE: city
    centerE: city
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: field
    northMid: road
    northBot: field
    westTop: field
    westMid: field
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: road
    centerNE: field
    centerN: road
    centerNW: field
    centerW: field
    centerSW: field
    centerS: road
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 5
    northTop: city
    northMid: city
    northBot: city
    westTop: field
    westMid: field
    westBot: field
    southTop: field
    southMid: field
    southBot: field
    eastTop: field
    eastMid: field
    eastBot: field
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: field
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 2
    northTop: field
    northMid: field
    northBot: field
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: field
    southBot: field
    eastTop: city
    eastMid: cityPennant
    eastBot: city
    center: city
    centerNE: city
    centerN: city
    centerNW: city
    centerW: city
    centerSW: city
    centerS: city
    centerSE: city
    centerE: city
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 1
    northTop: city
    northMid: city
    northBot: city
    westTop: field
    westMid: field
    westBot: field
    southTop: city
    southMid: city
    southBot: city
    eastTop: field
    eastMid: field
    eastBot: field
    center: city
    centerNE: city
    centerN: city
    centerNW: city
    centerW: city
    centerSW: city
    centerS: city
    centerSE: city
    centerE: city
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: field
    northMid: field
    northBot: field
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: field
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: field
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 2
    northTop: field
    northMid: field
    northBot: field
    westTop: field
    westMid: field
    westBot: field
    southTop: city
    southMid: city
    southBot: city
    eastTop: city
    eastMid: city
    eastBot: city
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: field
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: city
    northMid: city
    northBot: city
    westTop: field
    westMid: field
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: road
    eastBot: field
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: road
    centerSE: road
    centerE: road
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: field
    northMid: road
    northBot: field
    westTop: field
    westMid: road
    westBot: field
    southTop: field
    southMid: field
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: field
    centerNE: field
    centerN: road
    centerNW: road
    centerW: road
    centerSW: field
    centerS: field
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: field
    northMid: road
    northBot: field
    westTop: field
    westMid: road
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: dummy
    centerNE: field
    centerN: roadEnd
    centerNW: field
    centerW: roadEnd
    centerSW: field
    centerS: roadEnd
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 2
    northTop: city
    northMid: city
    northBot: cityPennant
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: field
    southBot: field
    eastTop: field
    eastMid: field
    eastBot: field
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: field
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: city
    northMid: city
    northBot: city
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: field
    southBot: field
    eastTop: field
    eastMid: field
    eastBot: field
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: field
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 2
    northTop: city
    northMid: city
    northBot: cityPennant
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: road
    eastBot: field
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: road
    centerSE: road
    centerE: road
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: city
    northMid: city
    northBot: city
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: road
    eastBot: field
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: field
    centerSW: field
    centerS: road
    centerSE: road
    centerE: road
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 1
    northTop: city
    northMid: city
    northBot: cityPennant
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: field
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: city
    centerNE: city
    centerN: city
    centerNW: city
    centerW: city
    centerSW: city
    centerS: city
    centerSE: city
    centerE: city
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 3
    northTop: city
    northMid: city
    northBot: city
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: field
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: city
    centerNE: city
    centerN: city
    centerNW: city
    centerW: city
    centerSW: city
    centerS: city
    centerSE: city
    centerE: city
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 2
    northTop: city
    northMid: city
    northBot: cityPennant
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: road
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: city
    centerNE: city
    centerN: city
    centerNW: city
    centerW: city
    centerSW: city
    centerS: roadEnd
    centerSE: city
    centerE: city
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 1
    northTop: city
    northMid: city
    northBot: city
    westTop: city
    westMid: city
    westBot: city
    southTop: field
    southMid: road
    southBot: field
    eastTop: city
    eastMid: city
    eastBot: city
    center: city
    centerNE: city
    centerN: city
    centerNW: city
    centerW: city
    centerSW: city
    centerS: roadEnd
    centerSE: city
    centerE: city
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 8
    northTop: field
    northMid: road
    northBot: field
    westTop: field
    westMid: field
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: field
    eastBot: field
    center: road
    centerNE: field
    centerN: road
    centerNW: field
    centerW: field
    centerSW: field
    centerS: road
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 9
    northTop: field
    northMid: field
    northBot: field
    westTop: field
    westMid: road
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: field
    eastBot: field
    center: field
    centerNE: field
    centerN: field
    centerNW: field
    centerW: road
    centerSW: road
    centerS: road
    centerSE: field
    centerE: field
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 4
    northTop: field
    northMid: field
    northBot: field
    westTop: field
    westMid: road
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: road
    eastBot: field
    center: dummy
    centerNE: field
    centerN: field
    centerNW: field
    centerW: roadEnd
    centerSW: field
    centerS: roadEnd
    centerSE: field
    centerE: roadEnd
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy
  - instances: 1
    northTop: field
    northMid: road
    northBot: field
    westTop: field
    westMid: road
    westBot: field
    southTop: field
    southMid: road
    southBot: field
    eastTop: field
    eastMid: road
    eastBot: field
    center: dummy
    centerNE: field
    centerN: roadEnd
    centerNW: field
    centerW: roadEnd
    centerSW: field
    centerS: roadEnd
    centerSE: field
    centerE: roadEnd
    cornerNE: dummy
    cornerNW: dummy
    cornerSW: dummy
    cornerSE: dummy


